USE wine_db;

CREATE TABLE inventory(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  user VARCHAR(100) NOT NULL,
  quantity VARCHAR(100) NOT NULL,
  wine VARCHAR(100) NOT NULL,
  vendor VARCHAR(100),
  PRIMARY KEY (id)
);
