DROP DATABASE IF EXISTS wine_db;
CREATE DATABASE wine_db;
USE wine_db;

CREATE TABLE wines(
  id INTEGER(11) AUTO_INCREMENT NOT NULL,
  vintage INTEGER(11),
  country VARCHAR(100) NOT NULL,
  region VARCHAR(100) NOT NULL,
  varietal VARCHAR(100) NOT NULL,
  producer VARCHAR(100) NOT NULL,
  ageability_index INTEGER(11),
  PRIMARY KEY (id)
);
