CREATE DATABASE IF NOT EXISTS wine_db;
USE wine_db;

CREATE TABLE IF NOT EXISTS wines(
  id INTEGER AUTO_INCREMENT NOT NULL,
  vintage INTEGER,
  country VARCHAR(100) NOT NULL,
  region VARCHAR(100) NOT NULL,
  varietal VARCHAR(100) NOT NULL,
  producer VARCHAR(100) NOT NULL,
  ageability_index INTEGER,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users(
  id INTEGER AUTO_INCREMENT NOT NULL,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS inventory(
  id INTEGER AUTO_INCREMENT NOT NULL,
  user_id INTEGER NOT NULL,
  quantity INTEGER NOT NULL,
  wine INTEGER NOT NULL,
  vendor VARCHAR(100),
  PRIMARY KEY (id),
  CONSTRAINT FK_inventory1 FOREIGN KEY (wine)
  REFERENCES wines(id),
  CONSTRAINT FK_inventory2 FOREIGN KEY (user_id)
  REFERENCES users(id)
);


CREATE TABLE IF NOT EXISTS history(
  id INTEGER AUTO_INCREMENT NOT NULL,
  wine INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  purchase_date DATE,
  notes VARCHAR(100),
  personal_rating INTEGER,
  ageability_index INTEGER,
  PRIMARY KEY (id),
  CONSTRAINT FK_history1 FOREIGN KEY (wine)
  REFERENCES wines(id),
  CONSTRAINT FK_history2 FOREIGN KEY (user_id)
  REFERENCES users(id)
);
